# Generated by Django 2.2 on 2020-08-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200807_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
