# Generated by Django 2.2 on 2020-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200807_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='date',
            field=models.DateTimeField(help_text='format (yyyy-mm-dd)'),
        ),
    ]
