# Generated by Django 2.2 on 2020-08-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('school', '0004_auto_20200807_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='vendor',
        ),
        migrations.AddField(
            model_name='eventitem',
            name='vendor',
            field=models.ManyToManyField(default=1, null=True, to='profiles.VendorProfile'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
