# Generated by Django 2.2 on 2020-09-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_vendorlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlist',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='vendorlist',
            name='users',
        ),
    ]
