# Generated by Django 2.2 on 2020-08-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='slug',
            field=models.SlugField(default='kid', unique=True),
            preserve_default=False,
        ),
    ]
