# Generated by Django 2.2 on 2020-08-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_kid_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='slug',
        ),
    ]
