# Generated by Django 2.2 on 2020-08-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_remove_kid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
