# Generated by Django 2.2 on 2020-08-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_kid_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
